services:
  app:
    build: .
    env_file: .env
    ports:
    - "8080:8080"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    networks:
    - database

networks:
  database:
    external: true
