[project]
name = "deadlock-data-api"
version = "0.1.0"
description = ""
authors = [
    { name = "Manuel Raimann", email = "raimannma@outlook.de" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.12.0",
    "boto3>=1.35.57",
    "cachetools>=5.5.0",
    "clickhouse-pool>=0.6.0",
    "discord-webhook>=1.3.1",
    "fastapi>=0.115.4",
    "granian>=1.6.3",
    "prometheus-fastapi-instrumentator>=7.0.0",
    "protobuf>=5.28.3",
    "psycopg2-binary>=2.9.10",
    "python-snappy>=0.7.3",
    "redis[hiredis]>=5.2.0",
    "sentry-sdk[fastapi]>=2.18.0",
    "uuid>=1.30",
    "valveprotos-py",
    "xmltodict>=0.14.2",
]

[dependency-groups]
dev = [
    "ruff>=0.7.3",
]

[tool.uv.sources]
valveprotos-py = { git = "https://github.com/deadlock-api/valveprotos-py" }

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = [
    "I", # isort-like rules
    "UP", # pyupgrade-like rules
]
