[tool.poetry]
name = "deadlock-data-api"
version = "0.1.0"
description = ""
authors = ["Manuel Raimann <raimannma@outlook.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.2"
uvicorn = "^0.30.6"
discord-webhook = "^1.3.1"
cachetools = "^5.5.0"
prometheus-fastapi-instrumentator = "^7.0.0"
redis = {extras = ["hiredis"], version = "^5.1.1"}
psycopg2-binary = "^2.9.10"
uuid = "^1.30"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
