[tool.poetry]
name = "deadlock-data-api"
version = "0.1.0"
description = ""
authors = ["Manuel Raimann <raimannma@outlook.de>"]
readme = "README.md"
packages = [
    { include = "deadlock_data_api", from = "." },
    { include = "protos", from = "protos" }
]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.2"
discord-webhook = "^1.3.1"
cachetools = "^5.5.0"
prometheus-fastapi-instrumentator = "^7.0.0"
redis = { extras = ["hiredis"], version = "^5.2.0" }
psycopg2-binary = "^2.9.10"
uuid = "^1.30"
protobuf = "^5.28.3"
clickhouse-pool = "^0.6.0"
sentry-sdk = { version = "^2.18.0", extras = ["fastapi"] }
python-snappy = "^0.7.3"
xmltodict = "^0.14.2"
valveprotos-py = { git = "https://github.com/deadlock-api/valveprotos-py" }
boto3 = "^1.35.57"
granian = "^1.6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
