name: lint-dockerfiles

on:
  push:
    branches:
    - master
  pull_request:
    paths:
    - 'Dockerfile'
    - 'docker-compose.yaml'

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint Docker Compose files
      run: docker compose config -q --no-interpolate || exit 1
    - name: Lint Dockerfiles
      uses: hadolint/hadolint-action@v3.1.0
      with:
        ignore: "DL3013"
